name: CI

on:
  workflow_dispatch:  # lets you manually run it
  push:
    branches: [ main ]  # runs on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # check out your code
      - run: echo "Hello, world!"   # simple test step
